# Generated by Django 4.2.17 on 2026-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmember_status_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_hours',
            field=models.IntegerField(blank=True, help_text='Actual hours spent on project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.IntegerField(blank=True, help_text='Estimated total hours for project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', help_text='Current project status', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
