# Generated by Django 4.2.17 on 2026-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_project_notification_related_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('story_assigned', 'Story Assigned'), ('story_updated', 'Story Updated'), ('project_invite', 'Project Invite'), ('deadline_reminder', 'Deadline Reminder'), ('comment_added', 'Comment Added'), ('project_updated', 'Project Updated')], default='general', max_length=50),
            preserve_default=False,
        ),
    ]
