# Generated by Django 4.2.17 on 2026-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_title_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('story_assigned', 'Story Assigned'), ('story_updated', 'Story Updated'), ('project_invite', 'Project Invite'), ('team_invitation', 'Team Invitation'), ('team_invitation_accepted', 'Team Invitation Accepted'), ('deadline_reminder', 'Deadline Reminder'), ('comment_added', 'Comment Added'), ('project_updated', 'Project Updated')], max_length=50),
        ),
    ]
