# Generated by Django 4.2.17 on 2026-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours spent on this task', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete this task', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Whether task is blocked by dependencies'),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='Task labels for categorization'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug Fix'), ('enhancement', 'Enhancement'), ('research', 'Research'), ('testing', 'Testing')], default='feature', help_text='Type of work for this task', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('testing', 'Testing')], default='todo', max_length=20),
        ),
    ]
