# Generated by Django 4.2.17 on 2026-04-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_task_actual_hours_task_estimated_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='taskattachment',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
