# Generated by Django 4.2.17 on 2026-04-25 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_alter_taskattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have marked this task as done.', related_name='completed_tasks_marked', to=settings.AUTH_USER_MODEL),
        ),
    ]
