# Generated by Django 4.2.17 on 2026-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['-priority', 'created_at'], 'verbose_name_plural': 'User stories'},
        ),
        migrations.AddField(
            model_name='userstory',
            name='acceptance_criteria',
            field=models.TextField(blank=True, default='', help_text='Definition of done for this story'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='business_value',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Business value for prioritization', max_length=50),
        ),
        migrations.AddField(
            model_name='userstory',
            name='story_points',
            field=models.IntegerField(blank=True, help_text='Story points for estimation', null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('testing', 'Testing')], default='todo', max_length=20),
        ),
    ]
